force-app/main/default/objects/Case/fields/CoIT_Causa_SIAB__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Causa_SIAB__c</fullName>
    <label>Causa SIAB</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Click_Severity__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Click_Severity__c</fullName>
    <label>Severidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bajo Impacto: 0 - 1 día</fullName>
            </value>
            <value>
                <fullName>Bajo Impacto: 0 - 3 días</fullName>
            </value>
            <value>
                <fullName>Bajo Impacto: 0 - 5 días</fullName>
            </value>
            <value>
                <fullName>Moderado: 6 - 19 días</fullName>
            </value>
            <value>
                <fullName>Alto Impacto: 20 o más días</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_CLV__c.field-meta.xml
<CustomField>
    <fullName>CoIT_CLV__c</fullName>
    <label>CLV - Cliente</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Cobertura_360__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Cobertura_360__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cobertura 360</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Codigo_Causa__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Codigo_Causa__c</fullName>
    <label>Codigo Causa</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Codigo_del_Producto__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Codigo_del_Producto__c</fullName>
    <label>Código del Producto</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Codigo_del_Ramo__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Codigo_del_Ramo__c</fullName>
    <label>Código del Ramo</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Codigo_Ubicacion__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Codigo_Ubicacion__c</fullName>
    <label>Código Ubicación</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1400</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Correo_Tomador__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Correo_Tomador__c</fullName>
    <label>Correo Tomador</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Documento_Tomador__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Documento_Tomador__c</fullName>
    <label>Documento Tomador</label>
    <length>27</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Estado_de_la_Llamada__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Estado_de_la_Llamada__c</fullName>
    <label>Estado de la Llamada</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Linea_de_Negocio__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Linea_de_Negocio__c</fullName>
    <label>Línea de Negocio</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Management_Type__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Management_Type__c</fullName>
    <label>Management Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gestión Automatica</fullName>
                <default>true</default>
                <label>Gestión Automatica</label>
            </value>
            <value>
                <fullName>Agendamiento</fullName>
            </value>
            <value>
                <fullName>Alertamientos</fullName>
            </value>
            <value>
                <fullName>Alto impacto</fullName>
            </value>
            <value>
                <fullName>Bajo/medio impacto</fullName>
            </value>
            <value>
                <fullName>Fallido Completado</fullName>
            </value>
            <value>
                <fullName>Gestión Automatica PoC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Nombre_Tomador__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Nombre_Tomador__c</fullName>
    <label>Nombre Tomador</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Nombre_Ubicacion__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Nombre_Ubicacion__c</fullName>
    <label>Nombre Ubicación</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bogota</fullName>
                <label>BOGOTA</label>
            </value>
            <value>
                <fullName>Santa Marta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Numero_de_la_Poliza__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Numero_de_la_Poliza__c</fullName>
    <label>Número de la Póliza</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Numero_de_Placa__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Numero_de_Placa__c</fullName>
    <label>Numero de Placa</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Numero_del_Siniestro__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Numero_del_Siniestro__c</fullName>
    <externalId>true</externalId>
    <label>Número del Siniestro</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Observaciones__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Observaciones__c</fullName>
    <label>Observaciones</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Opcion_de_Cobertura__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Opcion_de_Cobertura__c</fullName>
    <label>Opción de Cobertura</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Origen__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Origen__c</fullName>
    <label>Canal de solicitud</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Producto_Bolivar__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Producto_Bolivar__c</fullName>
    <label>Producto Bolivar</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 - INCENDIO TRADICIONAL</fullName>
            </value>
            <value>
                <fullName>100 - ASISTENCIA HOGAR</fullName>
            </value>
            <value>
                <fullName>109 - HOGAR PARA DISFRUTAR</fullName>
            </value>
            <value>
                <fullName>11 - TRADICIONAL EMPRESAR</fullName>
            </value>
            <value>
                <fullName>1111 - ASISTENCIA</fullName>
            </value>
            <value>
                <fullName>112 - MIGRACION HOGAR</fullName>
            </value>
            <value>
                <fullName>115 - HOGAR BANCARIO</fullName>
            </value>
            <value>
                <fullName>117 - HOGAR  PARA DISFRUTAR FUNCIONARIOS</fullName>
            </value>
            <value>
                <fullName>121 - HOGAR MULTICOMPA?IA</fullName>
            </value>
            <value>
                <fullName>125 - HOGAR VIVIR Y DISFRUTAR</fullName>
            </value>
            <value>
                <fullName>127 - HOGAR EL LIBERTADOR</fullName>
            </value>
            <value>
                <fullName>129 - HOGAR MODULAR</fullName>
            </value>
            <value>
                <fullName>140 - TODO RIESGO PARA CONSTRUCCION</fullName>
            </value>
            <value>
                <fullName>150 - TODO RIESGO CONSTRUCCION</fullName>
            </value>
            <value>
                <fullName>152 - EQUIPO Y MAQUINARIA</fullName>
            </value>
            <value>
                <fullName>173 - MULTIRIESGO PYMES</fullName>
            </value>
            <value>
                <fullName>200 - GARANTIAS CONSTRUCTORA BOLIVAR</fullName>
            </value>
            <value>
                <fullName>220 - ASISTENCIA HOGAR DIGITAL</fullName>
            </value>
            <value>
                <fullName>339 - HOGAR PROTECCION TOTAL</fullName>
            </value>
            <value>
                <fullName>600 - SEGURO AGRICOLA</fullName>
            </value>
            <value>
                <fullName>73 - HIPOTECARIOS COLPATRIA</fullName>
            </value>
            <value>
                <fullName>74 - CREDITOS HIPOTECARIOS</fullName>
            </value>
            <value>
                <fullName>75 - HIPOTECARIOS DAVIVIENDA</fullName>
            </value>
            <value>
                <fullName>76 - ALL RISK</fullName>
            </value>
            <value>
                <fullName>777 - E-PYMES</fullName>
            </value>
            <value>
                <fullName>799 - EDUCADORES PLUS</fullName>
            </value>
            <value>
                <fullName>8 - ROTURA DE MAQUINARIA</fullName>
            </value>
            <value>
                <fullName>923 - OFERTAS DE PROTECCION</fullName>
            </value>
            <value>
                <fullName>93 - MIDAS PLAN INDUSTRIAL</fullName>
            </value>
            <value>
                <fullName>94 - MULTIRIESGO PANIFICADORAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Producto_SIAB__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Producto_SIAB__c</fullName>
    <label>Producto SIAB</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Ramo_SIAB__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Ramo_SIAB__c</fullName>
    <description>Recibe la descripcion del ramo desde SIAB</description>
    <label>Ramo SIAB</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Riesgo__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Riesgo__c</fullName>
    <label>Riesgo-Placa</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Telefono_Tomador__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Telefono_Tomador__c</fullName>
    <label>Telefono Tomador</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Tipo_de_Asistencia__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Tipo_de_Asistencia__c</fullName>
    <label>Tipo de Asistencia</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CoIT_Was_Created_by_Integration__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Was_Created_by_Integration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Was Created by Integration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Autos.recordType-meta.xml
<RecordType>
    <fullName>Autos</fullName>
    <active>true</active>
    <businessProcess>inov8__PMT</businessProcess>
    <label>Autos</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Hogares.recordType-meta.xml
<RecordType>
    <fullName>Hogares</fullName>
    <active>true</active>
    <businessProcess>inov8__PMT</businessProcess>
    <label>Hogares</label>
</RecordType>

force-app/main/default/objects/Contact/fields/CoIT_N_Documento__c.field-meta.xml
<CustomField>
    <fullName>CoIT_N_Documento__c</fullName>
    <label>N. Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ServicioCreacionCaso.cls
@RestResource(urlMapping= '/api/crearCaso')
global with sharing class ServicioCreacionCaso {
    
    global class CrearCaseRequest { 
        public String CodigoProducto;
        public String CodigoRamo;
        public String RamoSIAB;
        public String ProductoSIAB;
        public String NumeroPoliza;
        public String CodigoCausa; 
        public String ProductoBolivar; 
        public String EstadoLlamada;
        public String CLV; 
        public String Origen; 
        public String Severidad; 
        public Boolean Cobertura360; 
        public String Observaciones; 
        public String TipoAsistencia;
                                  
        public String Riesgo; 
        public String NumeroSiniestro;
        public String OpcionCobertura; 
        public String NumeroPlaca; 
        public String NombreTomador;
        public String CorreoTomador;
                                   
        public String DocumentoTomador;
        public String TelefonoTomador; 
        public String NombreUbicacion;
        public String CodigoUbicacion;
        public String CausaSIAB ;
        public String LineaNegocio;
        public String Status; 
        public Boolean CreatedByIntegration;
    }
    
    @HttpPost 
    global static String crearCase(CrearCaseRequest request) {
        // Obtener el ID del RecordType
        Id recordTypeId = getRecordTypeId(request.CodigoRamo);
        
        // Verificar si se encontró el RecordType
        if (recordTypeId == null) {
            return 'Error: No se encontró un RecordType asociado al código de ramo: ' + request.CodigoRamo;
        }
        
        // Crear o actualizar el contacto
        Contact contacto = crearActualizarContacto(request);
        
        // Crear un nuevo caso con el RecordType obtenido
        return crearNuevoCaso(request, contacto, recordTypeId);
    }
    
    // Método para crear o actualizar un contacto
    global static Contact crearActualizarContacto(CrearCaseRequest request) {
        Contact[] contactosExistentes = [SELECT Id, LastName, CoIT_N_Documento__c, Email, Phone 
                                          FROM Contact 
                                          WHERE CoIT_N_Documento__c = :request.DocumentoTomador LIMIT 1];
        
        // Verificar si se encontró un contacto existente
        if (!contactosExistentes.isEmpty()) {
            // Actualizar los campos del contacto existente con los nuevos valores proporcionados
            Contact contactoExistente = contactosExistentes[0];
            contactoExistente.LastName = request.NombreTomador;
            contactoExistente.Email = request.CorreoTomador;
            contactoExistente.Phone = request.TelefonoTomador;
            // Actualizar otros campos del contacto si es necesario...
            
            // Actualizar el contacto existente
            update contactoExistente;
            
            return contactoExistente;
        } else {
            // Crear un nuevo contacto utilizando el nombre del tomador y el número de documento
            Contact nuevoContacto = new Contact(
                LastName = request.NombreTomador,
                CoIT_N_Documento__c = request.DocumentoTomador,
                Email = request.CorreoTomador,
                Phone = request.TelefonoTomador,
                AccountId = '0018M00000SM5EPQA1'
                // Otros campos del contacto que puedan ser necesarios...
            );
            
            // Insertar el nuevo contacto
            insert nuevoContacto;
            
            return nuevoContacto;
        }
    }
    
    // Método para crear un nuevo caso con el RecordType proporcionado
    global static String crearNuevoCaso(CrearCaseRequest request, Contact contacto, Id recordTypeId) {
        // Crear un nuevo registro de caso
        Case nuevoCaso = new Case(
            CoIT_Codigo_del_Producto__c = request.CodigoProducto,
            CoIT_Codigo_del_Ramo__c = request.CodigoRamo,
            CoIT_Ramo_SIAB__c = request.RamoSIAB,
            CoIT_Producto_SIAB__c= request.ProductoSIAB,
            CoIT_Numero_de_la_Poliza__c = request.NumeroPoliza,
            CoIT_Codigo_Causa__c = request.CodigoCausa,
            CoIT_Producto_Bolivar__c = request.ProductoBolivar,
            CoIT_Estado_de_la_Llamada__c = request.EstadoLlamada,
            CoIT_CLV__c = request.CLV,
            CoIT_Origen__c = request.Origen,
            CoIT_Click_Severity__c = request.Severidad,
            CoIT_Cobertura_360__c = request.Cobertura360,
            CoIT_Observaciones__c = request.Observaciones,
            CoIT_Tipo_de_Asistencia__c = request.TipoAsistencia,
            CoIT_Riesgo__c = request.Riesgo,
            CoIT_Numero_del_Siniestro__c = request.NumeroSiniestro,
            CoIT_Opcion_de_Cobertura__c = request.OpcionCobertura,
            CoIT_Numero_de_Placa__c = request.NumeroPlaca,
            CoIT_Nombre_Tomador__c = contacto.LastName,
            CoIT_Correo_Tomador__c = contacto.Email,
            CoIT_Documento_Tomador__c = contacto.CoIT_N_Documento__c,
            CoIT_Telefono_Tomador__c = contacto.Phone,
            CoIT_Nombre_Ubicacion__c = request.NombreUbicacion,
            CoIT_Codigo_Ubicacion__c = request.CodigoUbicacion,
            CoIT_Linea_de_Negocio__c = request.LineaNegocio,
            CoIT_Causa_SIAB__c = request.CausaSIAB,
            CoIT_Was_Created_by_Integration__c = request.CreatedByIntegration,
            Status = 'New',
            RecordTypeId = recordTypeId,
            ContactId = contacto.Id,
            CoIT_Management_Type__c = 'Gestión Automatica',
            AccountId = '0018M00000SM5EPQA1'// Asumiendo un estado por defecto para el caso
        );
        
        // Insertar el nuevo caso
        try {
            insert nuevoCaso;
            return 'Caso creado con éxito. ID: ' + nuevoCaso.Id + '. Contacto creado/actualizado: ' + contacto.Id;
        } catch (Exception e) {
            return 'Error al crear el caso: ' + e.getMessage();
        }
    }
    
    // Método para obtener el ID del RecordType basado en el código de ramo
    public static Id getRecordTypeId(String codigoRamo) {
        String recordTypeName;
        
        // Determinar el nombre del RecordType según el código de ramo
        if (codigoRamo == '10'|| codigoRamo == '70' || codigoRamo == '130'|| codigoRamo == '400' ) {
            recordTypeName = 'Autos';
        } else if (codigoRamo == '100' || codigoRamo == '120' ) {
            recordTypeName = 'Hogares';
        } else {
            recordTypeName = 'Master';
        }
        
        // Realizar una consulta SOQL para obtener el Id del RecordType utilizando el nombre del RecordType
        RecordType recordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Case' AND DeveloperName = :recordTypeName LIMIT 1];
        
        return (recordType != null) ? recordType.Id : null;
    }
}