force-app/main/default/objects/CoIT_Customer_Notificacion__c/CoIT_Customer_Notificacion__c.object-meta.xml
<CustomObject>
    <label>Customer Notificacion</label>
    <nameField>
        <displayFormat>CNM-{000000000}</displayFormat>
        <label>Customer Notificacion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Notificacions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CoIT_Customer_Notificacion__c/fields/CoIT_Case__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Customer Notificacions</relationshipLabel>
    <relationshipName>Customer_Notificacions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CoIT_Customer_Notificacion__c/fields/CoIT_Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Customer_Email__c</fullName>
    <label>Customer Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CoIT_Customer_Notificacion__c/fields/CoIT_Nombre_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Nombre_Cliente__c</fullName>
    <label>Nombre Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CoIT_Customer_Notificacion__c/fields/CoIT_Notificacion__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Notificacion__c</fullName>
    <label>Notificacion</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CoIT_Customer_Notificacion__c/fields/CoIT_Numero_Autorizacion__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Numero_Autorizacion__c</fullName>
    <label>Numero Autorizacion</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CoIT_Customer_Notificacion__c/fields/CoIT_Numero_Cliente__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Numero_Cliente__c</fullName>
    <label>Numero Cliente</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CoIT_Customer_Notificacion__c/fields/CoIT_Response__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Response__c</fullName>
    <label>Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CoIT_Customer_Notificacion__c/fields/CoIT_Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Service_Appointment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Appointment Number</label>
    <referenceTo>ServiceAppointment</referenceTo>
    <relationshipLabel>Customer Notificacions</relationshipLabel>
    <relationshipName>Customer_Notificacions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CoIT_Customer_Notificacion__c/fields/CoIT_Status_Service_Appointment__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Status_Service_Appointment__c</fullName>
    <label>Status Service Appointment</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CoIT_Customer_Notificacion__c/fields/CoIT_SurvercateTemplate__c.field-meta.xml
<CustomField>
    <fullName>CoIT_SurvercateTemplate__c</fullName>
    <label>Template</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CoIT_Customer_Notificacion__c/fields/CoIT_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Customer Notificacions</relationshipLabel>
    <relationshipName>Customer_Notificacions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomerNotificationService.cls
public class CustomerNotificationService {
    
    // Método para crear una notificación al cliente
    public static String createCustomerNotification(String customerPhone, String notificationMessage,String CustomerName, String NumeroSiniestro, String Response, String ServiceApp, String StatusSA, String Email,String WorkOrder,String LCase, String WhastAppsTem) {
        
    try {
        // Crear una instancia del objeto Customer Notifications
        CoIT_Customer_Notificacion__c newNotification = new CoIT_Customer_Notificacion__c();
        
        // Asignar valores a los campos del objeto
        newNotification.CoIT_Numero_Cliente__c = customerPhone;
        newNotification.CoIT_Notificacion__c = notificationMessage;
        newNotification.CoIT_Nombre_Cliente__c = CustomerName;
        newNotification.CoIT_Numero_Autorizacion__c = NumeroSiniestro;
        newNotification.CoIT_Response__c = Response;
        newNotification.CoIT_Service_Appointment__c = ServiceApp;
        newNotification.CoIT_Status_Service_Appointment__c = StatusSA;
        newNotification.CoIT_Customer_Email__c = Email;
        newNotification.CoIT_Work_Order__c = WorkOrder;
        newNotification.CoIT_Case__c = LCase;
        newNotification.CoIT_SurvercateTemplate__c = WhastAppsTem;
        
        
        // Insertar el registro en la base de datos
            insert newNotification;
            System.debug('Notificación al cliente creada con éxito.' + newNotification.Id);
            return 'Notificación al cliente creada con éxito.' + newNotification.Id;

        } catch (DmlException e) {
            System.debug('Error al crear la notificación al cliente: ' + e.getMessage());
            return 'Error al crear la notificación al cliente: ' + e.getMessage();

        }
    }
}