force-app/main/default/objects/AutoSchedule_ServiceAppointment__e/AutoSchedule_ServiceAppointment__e.object-meta.xml
<CustomObject>
    <description>Event to change auto schedule to true in a service appointment from work order</description>
    <label>Auto Schedule Service Appointment</label>
    <pluralLabel>Auto Schedule Service Appointments</pluralLabel>
</CustomObject>

force-app/main/default/objects/AutoSchedule_ServiceAppointment__e/fields/WorkOrderId__c.field-meta.xml
<CustomField>
    <fullName>WorkOrderId__c</fullName>
    <label>WorkOrderId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/FSL__Auto_Schedule__c.field-meta.xml
<CustomField>
    <fullName>FSL__Auto_Schedule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Schedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/CoIT_Numero_Siniestro__c.field-meta.xml
<CustomField>
    <fullName>CoIT_Numero_Siniestro__c</fullName>
    <externalId>true</externalId>
    <label>Número Siniestro</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestServiceAppointmentUpdater.cls
@isTest
public class TestServiceAppointmentUpdater {

    @testSetup
    static void setupTestData() {
        WorkOrder wo = new WorkOrder(
            CoIT_Numero_Siniestro__c = '123456', 
            Status = 'Open'
        );
        insert wo;

        ServiceAppointment sa = new ServiceAppointment(
            FSSK__FSK_Work_Order__c = wo.Id,
            FSL__Auto_Schedule__c = false
        );
        insert sa;
    }

    @isTest
    static void testServiceAppointmentUpdate() {
        WorkOrder wo = [SELECT Id FROM WorkOrder LIMIT 1];
        
        AutoSchedule_ServiceAppointment__e autoScheduleEvent = new AutoSchedule_ServiceAppointment__e(
            WorkOrderId__c = wo.Id
        );
        
        Test.startTest();
        EventBus.publish(autoScheduleEvent);
        Test.stopTest();

        ServiceAppointment updatedAppointment = [SELECT Id, FSL__Auto_Schedule__c FROM ServiceAppointment WHERE FSSK__FSK_Work_Order__c = :wo.Id LIMIT 1];
        
        System.assertEquals(true, updatedAppointment.FSL__Auto_Schedule__c, 'El campo FSL__Auto_Schedule__c debería estar en true');
    }
}